---
kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  name: nmstate-operator
  namespace: nmstate
  labels:
    nmstate.io: ""
---

---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  name: nmstate
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostNetwork: true
allowHostIPC: false
allowHostPID: false
allowHostPorts: false
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:nmstate:nmstate-handler
