---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  name: nmstate-operator
  namespace: {{ .OperatorNamespace }}
subjects:
- kind: ServiceAccount
  name: nmstate-operator
  namespace: {{ .OperatorNamespace }}
roleRef:
  kind: Role
  name: nmstate-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nmstate-operator
  namespace: {{ .OperatorNamespace }}
subjects:
- kind: ServiceAccount
  name: nmstate-operator
  namespace: {{ .OperatorNamespace }}
roleRef:
  kind: ClusterRole
  name: nmstate-operator
  apiGroup: rbac.authorization.k8s.io
