---
kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  name: nmstate-operator
  namespace: {{ .OperatorNamespace }}
  labels:
    nmstate.io: ""
